### ISSUE TITLE
Lsp_get_tdist

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#11]
qua_lsp.c

**Comment by teh117** [comment]
Estimated Clock Cycles: 212

**Comment by wcm129** [comment]
I've just completed this module.  It passes both behavioral and post-route on my machine with correct output.  There are no memory collisions or timing violations.

I will mark this issue for Parker to go behind me and reassure that everything is legit.  I will leave this issue for Parker to close once he is satisfied with its status.

On to the next one!  Well, hopefully anyways.

**Comment by wcm129** [comment]
Oh, and btw, uploading to the repository ASAP.

**Comment by jpj79** [comment]
This module runs correctly at 50 MHz in post route. I counted 104 clock cycles from start to done

**Comment by jpj79** [comment]
Behavioral Timing Samples:
START: 2,630 ns
DONE: 4,690 ns
TOTAL: 103 Clock cycles

START: 1,196,030 ns
DONE: 1,198,090 ns
TOTAL: 103 Clock Cycles
