### ISSUE TITLE
Copy

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#17]
util.c

**Comment by thrawn117** [comment]
Finished and uploaded the copy FSM and TB.
One interesting note: When the xAddr is set to 0, the first value copied is always zero.
I figured this to be un-noteworthy, as xAddr will never equal zero.

**Comment by jpj79** [comment]
Behavioral Timing Samples:
START: 2150 ns
DONE: 2550 ns
TOTAL: 20 clock cycles

START: 143,030 ns
DONE: 143,430 ns
TOTAL: 20 clock cycles
