### ISSUE TITLE
Int_lpc

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#20]
lpcfunc.c

**Comment by jpj79** [comment]
Correct output generated at 50 MHz. Uses 962 clock cycles from start to done

**Comment by jpj79** [comment]
Behavioral Timing Samples:
START: 4070 ns
DONE: 23,310 ns
TOTAL: 962 Clock cycles

START: 1,550,730 ns
DONE: 1,570,130 ns
TOTAL: 970 Clock Cycles
