### ISSUE TITLE
Int_qlpc

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#24]
lpcfunc.c

**Comment by jpj79** [comment]
Successfully executed at 50 MHz. Used 511 clock cycles from the start signal to the done signal.

**Comment by jpj79** [comment]
Behavioral Timing Samples:
START: 4070 ns
DONE: 14,250 ns
TOTAL: 509 Clock cycles

START: 923,150 ns
DONE: 933,330 ns
TOTAL: 509 Clock Cycles
