### ISSUE TITLE
perc_var

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#25]
pwf.c

**Comment by thrawn117** [comment]
I completed this function and tested it with at least 120 input values from the files.

**Comment by jpj79** [comment]
I have updated the files for perc_var. There are latches in the FSM that need to be removed. I posted a report of the warnings in the Synthesis Reports folder in our repository.

**Comment by jpj79** [comment]
perc_var has executed successfully, generating all correct outputs on Post-Route. The clock was set at 50 MHz for the previous test. Used 157 clock cycles.

**Comment by jpj79** [comment]
Behavioral Testing Samples:
START: 3,910 ns
DONE: 5,470 ns
TOTAL: 78 Clock cycles

START: 325,650 ns
DONE: 327,230 ns
TOTAL: 79 Clock Cycles
