### ISSUE TITLE
Residu

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#27]
filter.c

**Comment by wcm129** [comment]
Code is now ready for post route.  Tested in behavioral and works.

--Cooper

**Comment by jpj79** [comment]
There is an error in every 40th iteration appearing in Behavioral Simulation

**Comment by jpj79** [comment]
The error was being caused in the testbench. Cooper discovered the source and we added delays to fix the timing violations. Residu has passed post-route testing and I am closing the issue.

**Comment by jpj79** [comment]
Behavioral Timing Samples:
START: 122,670 ns
DONE: 154,710 ns
TOTAL: 1602 Clock cycles

START: 279,390 ns
DONE: 311,430 ns
TOTAL: 1602 Clock Cycles
