### ISSUE TITLE
Norm_Corr

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#31]
pitch.c

**Comment by jpj79** [comment]
Behavioral Testing Samples:
START: 37,790 ns
DONE: 265,750 ns
TOTAL: 11,498 Clock Cycles

START: 9,938,510 ns
DONE: 10,173,670 ns
TOTAL: 11,758 Clock Cycles

**Comment by jpj79** [comment]
Post-Route and Testing Timing Samples:
START: 37,790 ns
DONE: 265,750 ns
TOTAL: 11,498 Clock Cycles

START: 588,790 ns
DONE: 823,670 ns
TOTAL: 11,744 Clock Cycles

START: 1,757,470 ns
DONE: 1,992,630 ns
TOTAL: 11,758 Clock Cycles

**Comment by jpj79** [comment]
Completed Post-Route and Testing Simulation at 50 MHz
