### ISSUE TITLE
Inv_sqrt

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#33]
dspfunc.c

**Comment by thrawn117** [comment]
I completed the inv_sqrt function and tested at 50MHz with 3 test vectors and about 1500 values

**Comment by teh117** [comment]
Estimated clk cycles: 34

**Comment by jpj79** [comment]
Post-Route and Testing Time Samples:
START: 420 ns
DONE: 460 ns
TOTAL: 1< Clock cycles

START: 160,040 ns
DONE: 160,980 ns
TOTAL: 47 Clock Cycles

START: 354,700 ns
DONE: 355,240 ns
TOTAL: 27 Clock Cycles

Behavioral Timing Samples:
START: 503,400 ns
DONE: 503,900 ns
TOTAL: 25 Clock cycles

START: 299,200 ns
DONE: 299,740 ns
TOTAL: 27 Clock Cycles

START: 118,700 ns
DONE: 119,720 ns
TOTAL: 51 Clock Cycles
