### ISSUE TITLE
test_err

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#39]
cod_ld8k.c

**Comment by wcm129** [comment]
Tried figuring out CCs but couldn't find t0 or t0_frac defined anywhere???

I used "grep "#define t0" *" in Linux and couldn't find it defined.

**Comment by wolftrax84** [comment]
they're not constants. they're instantiated in cod_ld8k and used in multiple functions (eg Pitch_fr3, Enc_lag3, etc.) where they are probably set

**Comment by wcm129** [comment]
Makes sense.  I'll go look at it again.

**Comment by jpj79** [comment]
@wolftrax84 here is another error in synthesis that should be simple to correct: <br />
ERROR:HDLCompilers:28 - "test_err.v" line 226 'L_EXC_ERR' has not been declared

**Comment by jpj79** [comment]
Ran correctly in Post-Route and Testing Simulation at 50 MHz. From two sample I took it ran 10 and 12 clock cycles from start to done.

```
START: 1090 ns
DONE: 1290 ns
TOTAL: 10 clock cycles

START: 8210 ns
DONE: 8450 ns
TOTAL: 12 clock cycles
```

**Comment by jpj79** [comment]
Behavioral Timing Samples:
START: 1,090 ns
DONE: 1,270 ns
TOTAL: 9 Clock cycles

START: 360,050 ns
DONE: 360,270 ns
TOTAL: 11 Clock Cycles
