### ISSUE TITLE
Cor_h_X

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#42]
acelp_co.c

**Comment by thrawn117** [comment]
I finihsed the Cor_h_X function and tested with 3000 test values(app) across 3 test vectors at 50MHz. Synthesized and Post-Route tested.

**Comment by jpj79** [comment]
Behavioral Simulation Timing Samples:
START: 189,360 ns
DONE: 243,480 ns
TOTAL: 2706 clock cycles

START: 619,440 ns
DONE: 673,560 ns
TOTAL: 2706 clock cycles

**Comment by jpj79** [comment]
Post-Route and Timing Simulation completed at 50 MHz.
Timing Samples:
Start: 66,480 ns
Done: 120,600 ns
Total: 2706 clock cycles

Start: 496,560 ns
Done: 550,680 ns
Total: 2706 clock cycles

Start: 1,420,300 ns
Done: 1,474,680 ns
Total: 2719 clock cycles
