### ISSUE TITLE
Autocorrelation and Windowing

### ISSUE THREAD

**Issue by thrawn117** [nickrobinson/G729_CODE#54]
Autocorrelation and Windowing.
Test this one 1st.

**Comment by jpj79** [comment]
First run... Still working on setting up each of these projects for testing
Total memory usage is 210408 kilobytes

Number of errors   :    1 (   0 filtered)
Number of warnings :   60 (   0 filtered)
Number of infos    :   10 (   0 filtered)

Process "Synthesize - XST" failed

ERROR:Xst:528 - Multi-source in Unit 'autocorrFSM' on signal 'overflowLD'; this signal is connected to multiple drivers.

**Comment by thrawn117** [comment]
Hmmm...I wasn't getting that error before.
That error means that the overflowLD signal is being changed by two different always blocks or in two different files, which it shouldn't be.

**Comment by thrawn117** [comment]
Hmmm...I wasn't getting that error before.
That error means that the overflowLD signal is being changed by two different always blocks or in two different files, which it shouldn't be.

**Comment by jpj79** [comment]
Found an error within the autocorrFSM.v that dealt with multi-sourcing. The error is fixed thanks to Zach. Here is a new discovery I came across during simulation. 

**For a side note the simulation output came out as expected but this latter half of the log file is startling.. It occurs when the mux switches inputs from the Testbench to the FSM. This problem might be an issue later but I will consult Dr. Morris for any suggestions

```
14750 CORRECT:  x[         72] = 0000, y[         72] = 009d
14950 CORRECT:  x[         73] = 2d41, y[         73] = 1592
15150 CORRECT:  x[         74] = c000, y[         74] = e0ec
15350 CORRECT:  x[         75] = 2d41, y[         75] = 166a
15550 CORRECT:  x[         76] = 0000, y[         76] = ff69
15750 CORRECT:  x[         77] = d2bf, y[         77] = ea73
15950 CORRECT:  x[         78] = 4000, y[         78] = 1f18
16150 CORRECT:  x[         79] = d2bf, y[         79] = e99a
blk_mem_gen_v2_4 collision detected at time: 40250000, A write address: 0, B  ra`d address: 0
blk_mem_gen_v2_4 collision detected at time: 40290000, A write address: 1, B  ra`d address: 1
blk_mem_gen_v2_4 collision detected at time: 40330000, A write address: 2, B  ra`d address: 2
blk_mem_gen_v2_4 collision detected at time: 40370000, A write address: 3, B  ra`d address: 3
blk_mem_gen_v2_4 collision detected at time: 40410000, A write address: 4, B  ra`d address: 4
```

**Comment by nickrobinson** [comment]
Future note, it might be a good idea to keep the author of the module tagged even while testing to allow Parker to be able to see who he needs to talk to if their is an error a little more transparent.

**Comment by jpj79** [comment]
Currently there are latches showing up during synthesis in the following files:
    hammingWindowMemory.v
    autocorrFSM.v

I have a .OUT file I will give to you that shows what exactly needs to be worked on.

**Comment by jpj79** [comment]
Executing at a clock frequency of 50 MHz on post-route with Correct output all the way through.

**Comment by thrawn117** [comment]
Parker, I had to completely rewrite this FSM and it's gonna need to be tested again in post_Route, but synthesis worked correctly.
It's just the Post-Route is gonna take a long time.

**Comment by jpj79** [comment]
Alright I am building it now.

**Comment by jpj79** [comment]
I rebuilt the project from the files currently off of the repository. I am not being able to simulate it in Behavioral without errors from iterations 0 through 32. I am using the test files autocorr_in.out and autocorr_out.out found in the folder 
    \G729_CODE\Autocorrelation and Windowing\Autocorr+Preproc

**Comment by jpj79** [comment]
Behavioral Timing Sample:
START: 19,310 ns
DONE: 205,470 ns
TOTAL: 9308 Clock cycles

START: 845,470 ns
DONE: 1,031,390 ns
TOTAL: 9296 Clock Cycles
