### ISSUE TITLE
div_s

### ISSUE THREAD

**Issue by jpj79** [nickrobinson/G729_CODE#60]
# These latches need to be removed:

Synthesizing Unit <div_s>.

WARNING:Xst:737 - Found 32-bit latch for signal <subouta>. Latches may be generated from incomplete case or if statements. We do not recommend the use of latches in FPGA/CPLD designs, as they may lead to timing problems.

WARNING:Xst:737 - Found 32-bit latch for signal <suboutb>. Latches may be generated from incomplete case or if statements. We do not recommend the use of latches in FPGA/CPLD designs, as they may lead to timing problems.

WARNING:Xst:737 - Found 32-bit latch for signal <temp_L_out>. Latches may be generated from incomplete case or if statements. We do not recommend the use of latches in FPGA/CPLD designs, as they may lead to timing problems.

**Comment by wolftrax84** [comment]
Fixed
