### ISSUE TITLE
Lsp_pre_select

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#7]
qua_lsp.c

**Comment by teh117** [comment]
Estimated Clock Cycles: 5506

**Comment by thrawn117** [comment]
Tested, and placed in Qua_Lsp

**Comment by nickrobinson** [comment]
@teh117 Hey I need to ask you a question about your cand output reg for this function I think we may have to rework this just a bit to get it to work correctly with Relspwed.
